<a href="https://colab.research.google.com/github/lwalker8264-cyber/My_Portfolio/blob/main/brazillian_e_com/Brazilian__Case_Study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Brazilian E-Commerce Project

## The goal and vision

The goal of this project is to clean a particularly messy dataset of a Brazilian E-Commerce company, clean all of the data, the explore the data to find any useful trends. This will be done using SQL queries via BigQuery. After this is done I will translate the data in to easily understandable charts to better explain how I achieved my data and what the trends could potentially mean to this companies business needs.

## Step 1

The first step to this process is to retrieve the dataset and upload it into BigQuery. After this is done I'll look into the various tables and their schema to find out what kind of data they hold and how it can be analyzed.

## Step 2

The next step is to clean any of the data that I intend to work with to ensure that any results that I get are true and accurate. Usually I would take the tables clean them fully first and then begin to Analyze. However since I'm using the sandbox version of BigQuery for this project I will instead be cleaning the data while I'm analyzing the data for trends in the same code block.

So the first table I will be taking a look at is the Olist_geolocation table to try and find if there is any correlation between customers and a specific area.

To do this we'll use the query below.

In [ ]:
WITH state_counts AS (
  SELECT
    UPPER(TRIM(geolocation_state)) AS cleaned_state,
    COUNT(*) AS total_entries
  FROM
    willy-worldstar.Brazilian_E_Commerce_Data_Set.Olist_Geolocation
  GROUP BY
    1
)
SELECT
  cleaned_state,
  CASE cleaned_state
    WHEN 'SP' THEN 'São Paulo'
    WHEN 'RJ' THEN 'Rio de Janeiro'
    WHEN 'MG' THEN 'Minas Gerais'
    WHEN 'RS' THEN 'Rio Grande do Sul'
    WHEN 'PR' THEN 'Paraná'
    ELSE 'Other Brazilian State'
  END AS state_full_name,
  ROUND( total_entries * 100 / SUM(total_entries) OVER(),  2) AS percentage_of_total
FROM
  state_counts
ORDER BY total_entries DESC

So to break down this code first I'll explain what the idea is. I want to compare the amount of orders to state in which the orders were made to see if a particular state contains a higher percentage of customer which would then let the company know where to best launch their marketing efforts.

In order to do this I will need to have multiple aggregate functions compared against each other. For this I will be using a Common Table Expression or a CTE which allows me to make a temporary table where I will perform one aggregate function and then compare it to another table.

This is the first section of the code as shown below.

In [ ]:
WITH state_counts AS (
  SELECT
    UPPER(TRIM(geolocation_state)) AS cleaned_state,
    COUNT(*) AS total_entries
  FROM
    willy-worldstar.Brazilian_E_Commerce_Data_Set.Olist_Geolocation
  GROUP BY
    1
)

This code starts with a WITH AS expression that signifies the start of my CTE. Inside the WITH AS expression I name my CTE "state_counts" then I open parenthesis and start with SELECT I then input UPPER(TRIM(geo_location)). This calls for the geolocation_state column and first applies the TRIM function to the column which wil cut off any blank spaces that could lead to a potentiall error. Then an UPPER function is applied to that data in order to transform the casing of the state abbreviations to all uppercase and make them uniform. After that I will give this clean data an alias using AS "cleaned_state" to make the clean data more easily identifiable. Next in the SELECT clause I want the total number of state entries made so I use the code COUNT(*) and give it the alias total entries. The COUNT function followed by (*) ensures that all of the entries are counted.

After that we move to the FROM clause which tells the Query from which table we are pulling these data column form. In this case it is from willy-worldstar.Brazilian_E_Commerce_Data_Set.Olist_Geolocation.

After that we move to the GROUP BY clause which is neccesary because we are using the aggregate function COUNT in our SELECT clause. Since we want our aggregate function to count the amount of state entries and since we want it to be clean data that we are pulling it from, we are going to group by clean_state which we just recently cleaned.

This CTE will give us clean counted data of the number of state entries so that we can compare and find out the percent of orders for each state.

** Next we are going to use the code below to pull from the column total_entries we made in our CTE named state_counts and compare each state's count to the total_entries to find the average percentage of each state's number of entries.

In [ ]:
SELECT
  cleaned_state,
  CASE cleaned_state
    WHEN 'SP' THEN 'São Paulo'
    WHEN 'RJ' THEN 'Rio de Janeiro'
    WHEN 'MG' THEN 'Minas Gerais'
    WHEN 'RS' THEN 'Rio Grande do Sul'
    WHEN 'PR' THEN 'Paraná'
    ELSE 'Other Brazilian State'
  END AS state_full_name,
  ROUND( total_entries * 100 / SUM(total_entries) OVER(),  2) AS percentage_of_total
FROM
  state_counts
ORDER BY total_entries DESC

  Now I will start with selecting our created alias total_entries in the FROM clause.

  Next in the SELECT clause my first line will be clean_state to add or clean state date to the table we are building.

  Moving to the next line I will build the formula needed to get our averages.

In [ ]:
ROUND( total_entries * 100 / SUM(total_entries) OVER(),  2) AS percentage_of_total

  To do that I'll multiply the total number of specific state entries by 100, then divide that by the sum of the total numbers of entries by using the SUM function. Next in our line of code I will use the clause OVER in order to take away the need for a GROUP BY clause. This is because we want to be able to see the percentage of the numbers of entries and the total amount of entries on the same table.

  Finally we'll use ROUND to round the percentage to a whole number and then give this line of code the alias Percentage_of_total.

In [ ]:
SELECT
  cleaned_state,
  CASE cleaned_state
    WHEN 'SP' THEN 'São Paulo'
    WHEN 'RJ' THEN 'Rio de Janeiro'
    WHEN 'MG' THEN 'Minas Gerais'
    WHEN 'RS' THEN 'Rio Grande do Sul'
    WHEN 'PR' THEN 'Paraná'
    ELSE 'Other Brazilian State'
  END AS state_full_name,

 After that we will need to go back in to the SELECT statement and clean up our data so that there will be no errors in our query. This is because this data comes from brazil and the database I'm using will not be able to read the abbreviations correctly for Brazilian states.

 To fix this we are going to put in a CASE statement. In this CASE statement we will address these by giving the correct name in each situation.

 I'll accomplish this by using WHEN to address the abbreviation and THEN to give the correct state name.

 Next I'll put in a ELSE statement in case a different abbreviation I didn't expect comes up or I missed an entry. If this happens I will make it easily identifiable by using the ELSE statement  to give the name ' Other brazilian state' to any of these outliers situations that may occur.

 Finally we'll end the codeblock with END and give this codeblock the alias state_full_name.

In [ ]:
ORDER BY total_entries DESC

  After that we will use an ORDER BY clause to order my Table by the highest number of total_entries. I'll do this by adding DESC which will ensure that the table will descend from the highest value to the lowest.

Now we will look at the results of this query which is shown below.

In [ ]:
%%bigquery df_states --project willy-worldstar
WITH state_counts AS (
  SELECT
    UPPER(TRIM(geolocation_state)) AS cleaned_state,
    COUNT(*) AS total_entries
  FROM
    willy-worldstar.Brazilian_E_Commerce_Data_Set.Olist_Geolocation
  GROUP BY
    1
)
SELECT
  cleaned_state,
  CASE cleaned_state
    WHEN 'SP' THEN 'São Paulo'
    WHEN 'RJ' THEN 'Rio de Janeiro'
    WHEN 'MG' THEN 'Minas Gerais'
    WHEN 'RS' THEN 'Rio Grande do Sul'
    WHEN 'PR' THEN 'Paraná'
    ELSE 'Other Brazilian State'
  END AS state_full_name,
  ROUND( total_entries * 100 / SUM(total_entries) OVER(),  2) AS percentage_of_total
FROM
  state_counts
ORDER BY total_entries DESC
LIMIT 5

Query is running:   0%|          |

Downloading:   0%|          |

In [ ]:

df_states

  cleaned_state    state_full_name  percentage_of_total
0            SP          São Paulo                40.42
1            MG       Minas Gerais                12.63
2            RJ     Rio de Janeiro                12.11
3            RS  Rio Grande do Sul                 6.18
4            PR             Paraná                 5.78

As you can see our SQL query shows the top 5 states that the business gets its orders from. With this knowledge they can make decisions that are much better informed whether they want to focus their efforts on the market that they are most established or if they want to increase their hold on the next most established.

## Portion 2

  The next trend I want to explore is the customer_id's number of purchases to see if the company has a high end customer that makes a large number of purchases or possibly even multiple high end customer.

  To do this we'll be using the SQL query below.

In [ ]:
SELECT
  DISTINCT customers.customer_unique_id AS unique_customer_id,
  COUNT(order_data.order_id) AS items_bought
FROM
  willy-worldstar.Brazilian_E_Commerce_Data_Set.Olist_Order_Dataset AS order_data
INNER JOIN
  willy-worldstar.Brazilian_E_Commerce_Data_Set.Olist_Customers AS customers ON order_data.customer_id = customers.customer_id
GROUP BY
  unique_customer_id
ORDER BY
  items_bought DESC

  The first thing I need to do is choose the table I'll be pulling from in the FROM clause which in this case is willy-worldstar.Brazilian_E_Commerce_Data_set.Olist_Order_Dataset.

  Which you can see with this line of code below.

  willy-worldstar.Brazilian_E_Commerce_Data_Set.Olist_Order_Dataset AS order_data

  Next I will give the alias order_data to the FROM clause using the AS keyword.

Next because we are wanting to compare the number of purchases with the customer_id we'll need to bring another table in to the query and to do this I'll be using the INNER JOIN clause. You can see this in the code line below.

In [ ]:
INNER JOIN
  willy-worldstar.Brazilian_E_Commerce_Data_Set.Olist_Customers AS customers ON order_data.customer_id = customers.

To do this the INNER JOIN is going to use the customer column on the Olist set and match it to the customer_id column on the order_data set. While we're at it we'll give the column willy-worldstar-Brazilian_E_Commerce_Data_Set.Olist_Customers the alias customers to make it easier to reference.

After that we will move to the SELECT clause and choose which columns we want to display in our table. To do this I'll use the code below.

In [ ]:
SELECT
  DISTINCT customers.customer_unique_id AS unique_customer_id,
  COUNT(order_data.order_id) AS items_bought

So to break this down first we are going to select the column customer_unique_id from the customers table and give it the alias unique_customer_id to make it easier to reference. After we do this we are going to apply the DISTINCT operator  to ensure that the data is clean and there is no duplicates.

  One very important thing to note is that in the dataset there is 2 columns in regards to customer_id. These 2 columns are customer_id and unique_customer_id. The standard customer_id which a new one is generated every time a purchase is made. So if we want to ensure we are finding the number of times a customer has repeatedly made purchases we need to make sure that we use the customer_unique_id column and then apply the DISTINCT operator to make sure there is not duplicates of the unique_customer_id records.

After this we want to count the number of times each customer places and order and to do this we use the code below.

In [ ]:
COUNT(order_data.order_id) AS items_bought

  After we use COUNT to count up all of the orders placed via their id's and give it the Alias items_bought.

  Next we have to include a GROUP BY clause due to the aggregation used in the SELECT clause. In the group by clause we will group by unique_customer_id so that our table will by ordered by customer id's. You can see this in the code below.

In [ ]:
GROUP BY
  unique_customer_id

  Finally we will need to add an ORDER BY clause to ensure that we see the largest number of orders first. To do this we will order by items_bought and we will add DESC before items_bought so that the largest number of items_bought per customer_id will be displayed first.

  The final thing we will need to do to complete this query is to add an ORDER BY clause. This is because we want our results table to be displayed by a particular column, which in this case will be items_bought. Next we will add the function DESC before items_bought so that the results would be organized by the highest number of items bought first. You can see this in the code block below.

In [ ]:
ORDER BY
  items_bought DESC

After that we will take a look at the table our query produces and what trends it shows us.

In [ ]:
%%bigquery --project willy-worldstar
SELECT
  DISTINCT customers.customer_unique_id AS unique_customer_id,
  COUNT(order_data.order_id) AS items_bought
FROM
  willy-worldstar.Brazilian_E_Commerce_Data_Set.Olist_Order_Dataset AS order_data
INNER JOIN
  willy-worldstar.Brazilian_E_Commerce_Data_Set.Olist_Customers AS customers ON order_data.customer_id = customers.customer_id
GROUP BY
  unique_customer_id
ORDER BY
  items_bought DESC

Query is running:   0%|          |

Downloading:   0%|          |

                     unique_customer_id  items_bought
0      8d50f5eadf50201ccdcedfb9e2ac8455            17
1      3e43e6105506432c953e165fb2acf44c             9
2      ca77025e7201e3b30c44b472ff346268             7
3      6469f99c1f9dfae7733b25662e7f1782             7
4      1b6c7548a2a1f9037c1fd3ddfed95f33             7
...                                 ...           ...
96091  9343f3f5b50a126c8ca3d34b83d69197             1
96092  0c39cc8984e30ac517c69a6671be71a7             1
96093  e6925d3e39cebd0f699008b248e58361             1
96094  c90ae099730477670c18582c8b45550d             1
96095  c9d7e6e0c6eaa74de5ba8d684240260b             1

[96096 rows x 2 columns]

 What can be seen from our table is that there isn't really any particular customers that purchase a large number of items, however there a few repeat customers. From this data we know there are not very repeat customers and that their customer loyalty  is weak and could use improvement. Also the top customers can be reached out to in order to see why they are repeat customers. A loyalty program is an actionable response that I would recommend backed by this table.

 We will emphasize this trend by linking out Tableau Public to display our graphs pointing out this fact.

In [ ]:
from IPython.display import IFrame

# 1. Take your original dashboard link
# 2. Make sure it ends with ?:embed=y&:showVizHome=no
tableau_url = "https://public.tableau.com/views/Book3_Items_Bought/Sheet3?:language=en-US&publish=yes&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link?:embed=y&:showVizHome=no"

# 3. Render it inside the IFrame
IFrame(src=tableau_url, width=900, height=600)

In [ ]:
from IPython.display import IFrame


tableau_url = "https://public.tableau.com/views/Book3_Items_Bought_2/Sheet4?:language=en-US&publish=yes&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link?:embed=y&:showVizHome=no"


IFrame(src=tableau_url, width=900, height=600)

  This wraps up the technical clean up and analysis of the Brazilian E-Commerce data set for this project. This is because to add too many more trends to this analysis would make the presentation convoluted. A good analysis and then presentation to either stake holders or the company shouldn't contain several varying trends but more so a couple hard hitting trends that can be impactfully presented with actionable suggestions. To break it down even further, one problem at a time starting with the most prevalent  and actionable trends to be targeted first.